"""empty message

Revision ID: 72f99be8cbc1
Revises: 8daf6437564a
Create Date: 2021-12-12 15:04:39.332302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f99be8cbc1'
down_revision = '8daf6437564a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('city', sa.String(length=250), nullable=True))
    op.add_column('customer', sa.Column('county', sa.String(length=250), nullable=True))
    op.add_column('customer', sa.Column('state', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'state')
    op.drop_column('customer', 'county')
    op.drop_column('customer', 'city')
    # ### end Alembic commands ###
